[package]
name = "amvm"
version = "0.1.0"
edition = "2021"
description = "Apika's My Virtual Machine. A virtual machine with Intermediate Lenguage"
license = "MIT"
default-run = "amvm"

[dependencies]
nom = "7.1.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
